<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AdarshPunjala" name="Default test" tests="1" failures="1" timestamp="20 Jan 2017 14:54:22 GMT" time="0.098" errors="0">
  <testcase name="login" time="0.0" classname="chrome.ExcelSheetData">
    <failure type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] chrome.ExcelSheetData.passdata(java.lang.String[][]) throws java.lang.Exception parameters unresolved:  at 0 type class [[Ljava.lang.String;
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] chrome.ExcelSheetData.passdata(java.lang.String[][]) throws java.lang.Exception parameters unresolved:  at 0 type class [[Ljava.lang.String;

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:156)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:106)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:436)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Default test -->
